### ISSUE TITLE
can't remove the settings

### ISSUE THREAD

**Issue by jrep20** [alexander-shch/WebStorm-php-Syntax-Highlight-with-WordPress-functions#2]
I installed this hoping for PHP syntax highlighting, but it broke my Webstorm 2016.3 and I can't seem to remove whatever settings were installed. Can you explain how to undo this?

**Comment by Keithcat767** [comment]
I ran into the same issue. On my Mac, I went to `Library/Preferences/WebStorm2016.3/filetypes/` and removed the PHP.xml file. This allowed me to open PHP files again.

**Comment by alexander-shch** [comment]
Hi guys.
Really sorry to hear that you had problems with the Import.
This is a pretty old file and since then I moved to PHPStorm and didn't update it.

But if I remember correctly.
Go to: 
Settings -> Editor -> File Types
And remove the php file type which was appended.
This should restore what ever happened.

**Comment by alexander-shch** [comment]
In my PhpStorm Directory, I did find these folders.

php.class.name
php.constant.name
php.function.name
php.method.name
php.namespace.inheritance
php.trait.usage
php.variable.name
phpunitgroupsindex

Not sure how JetBrains changed the code for the new storm versions but If you would like I can upload these folders for you to try and implant them into your WebStorm directory.

In my case (Win 10)
Users\USER_NAME\.PhpStorm2016.2\system\index

Just let me know
